language: python

env:
  global:
    - TWINE_USERNAME="anthrotype"
    - secure: CMCLOo9Y8eKK8BfYZeHfclvwx5uJX7078/nLVFF8qZJssopTA34kuJvIOG3UIGpN0Q/iy+GwKVcEHOA59aOuS+lLUjX9U6O/p9Byxg4hNrYQkqEGUS+2eUvGII9ko03ZzWpX4uGSvhRx6013cCNM3iCGtcoCQhMYsIkxAipVXBEdeo78km9lN4FEvdLy4P9KcRP8rEFWvIOg+zrvQr8i5M8UMLloL5E+AY0q+W+qVCGx6k2hxt5UGqEiffoC99Y36iXlge932ftAxOS3Yf5seh8lN5RlTnJ3fB6cqkXV28ZNi390R1kGLRQSos1bqvk3KPk3ItfSjqVJtzkKemtWbZcu0KfUzdbvjugNudfxSHYxs5rpj3ncPFC8C4Os94ICgr+HrgTODj8PBfwfm1bgKU7RboHzPa0pCPboaO1Hxac/c2BNzQPvtO8xbOw/ehIPSNTzZf/zszhcULB17nx6OUoWZKhwXw217ZUlSCd9Vo/nxx7IYktkmaydAKUbBoMBUXq6b+DgMHGpt4fRtQ/6CqU35HIvdcyiuSfFck/17Wep26GQ35JJunE/w3KNES6bcWlUShyJyk/meZwyCOEqg3n9OCax9GedO28DsQML7WK1L36JFDXk2FWq+noz/gts99u4RgBOekQ/ggRIsMFKeW0XzqYuYTqorHmbLVfYPLE=

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-cov
    - python: 3.6
      env: TOXENV=py36-cov
    - python: 3.7
      env:
        - TOXENV=py37-cov
        - BUILD_DIST=true
      dist: xenial

install:
  - pip install tox
  - pip install coveralls

script:
  - tox

after_success:
  - coverage combine
  - coveralls
  # if it's a tagged commit, upload distribution packages to pypi
  - |
    if [ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_REPO_SLUG" == "LettError/MutatorMath" ] && [ "$BUILD_DIST" == true ]; then
        pip install --upgrade twine pip setuptools wheel
        python setup.py sdist
        pip wheel --no-deps --wheel-dir dist .
        twine upload dist/*.whl dist/*.zip
    fi
