language: python
sudo: required
python:
  - "2.7"
before_install:
  - git clone https://github.com/typesupply/defcon.git --branch ufo3
  - git clone https://github.com/typesupply/fontMath.git --branch ufo3
  - git clone https://github.com/robofab-developers/robofab.git --branch ufo3k
  - git clone https://github.com/unified-font-object/ufoLib.git
  - git clone https://github.com/behdad/fonttools.git
install:
  - cd defcon; python setup.py install; cd ..
  - cd fontMath; python setup.py install; cd ..
  - cd robofab; python install.py; cd ..
  - cd fonttools; python setup.py install; cd ..
  # MutatorMath
  - python setup.py install
  - pip install coveralls
script:
  - cd Lib/mutatorMath/test/ufo
  - coverage run --parallel-mode --source=mutatorMath test.py
after_success:
  - coverage combine
  - coveralls
