language: python
sudo: required
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install -v .
script:
  - coverage run --parallel-mode --source=mutatorMath Lib/mutatorMath/test/ufo/test.py
after_success:
  - coverage combine
  - coveralls
